apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.serverName | lower }}-server
spec:
  selector:
    matchLabels:
      app:  {{ .Values.serverName | lower }}-app
  template:
    metadata:
      labels:
        app:  {{ .Values.serverName | lower }}-app
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: lloesche/valheim-server:latest
        name: vailheim-server
        env:
        - name: SERVER_NAME
          value: {{ .Values.serverName }}
        - name: WORLD_NAME
          value: {{ .Values.worldName }}
        - name: SERVER_PASS
          value: {{ .Values.password }}
        - name: SERVER_PORT
          value: "{{ .Values.serverPort1 }}"
        - name: SERVER_PUBLIC
          value: "{{ .Values.serverPublic | default "false" }}"
        ports:
        - containerPort: {{ .Values.serverPort1 | default "2456" }}
          name: game1
          protocol: UDP
        - containerPort: {{ .Values.serverPort2 | default "2457" }}
          name: game2
          protocol: UDP
        - containerPort: {{ .Values.serverPort3 | default "2458" }}
          name: game3
          protocol: UDP
        {{ if eq .Values.storage.kind "hostvol" }}
        volumeMounts:
        - mountPath: /config
          name: gamefiles
        {{ end }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
      {{ if eq .Values.storage.kind "hostvol" }}
      volumes:
      - name: gamefiles
        hostPath:
          path: {{ .Values.storage.hostvol.path }}
          type: Directory
      {{ end }}

