apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverName | lower }}-service
spec:
  ports:
  - name: game1
    port: {{ .Values.serverPort1 | default "2456" }}
    targetPort: {{ .Values.serverPort1 | default "2456" }}
    protocol: UDP
  - name: game2
    port: {{ .Values.serverPort2 | default "2457" }}
    targetPort: {{ .Values.serverPort2 | default "2457" }}
    protocol: UDP
  - name: game3
    port: {{ .Values.serverPort3 | default "2458" }}
    targetPort: {{ .Values.serverPort3 | default "2458" }}
    protocol: UDP
  type: {{ .Values.networking.serviceType }}
  selector:
    app: {{ .Values.serverName | lower }}-app
